/* tslint:disable */
/* eslint-disable */
/**
 * AYS API
 * AYS API Description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ClassDto
 */
export interface ClassDto {

    /**
     * @type {string}
     * @memberof ClassDto
     */
    name: string;

    /**
     * @type {any}
     * @memberof ClassDto
     */
    teachers?: any;

    /**
     * @type {any}
     * @memberof ClassDto
     */
    students?: any;
}
