/* tslint:disable */
/* eslint-disable */
/**
 * AYS API
 * AYS API Description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateStudentDto
 */
export interface CreateStudentDto {

    /**
     * @type {Array<string>}
     * @memberof CreateStudentDto
     */
    parents?: Array<string>;

    /**
     * @type {string}
     * @memberof CreateStudentDto
     */
    classid?: string;

    /**
     * @type {number}
     * @memberof CreateStudentDto
     */
    studentid: number;

    /**
     * @type {string}
     * @memberof CreateStudentDto
     */
    name: string;

    /**
     * @type {string}
     * @memberof CreateStudentDto
     */
    gender: CreateStudentDtoGenderEnum;

    /**
     * @type {number}
     * @memberof CreateStudentDto
     */
    birth: number;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateStudentDtoGenderEnum {
    Male = 'male',
    Female = 'female'
}

