/* tslint:disable */
/* eslint-disable */
/**
 * AYS API
 * AYS API Description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateBulletinDto
 */
export interface CreateBulletinDto {

    /**
     * @type {string}
     * @memberof CreateBulletinDto
     */
    title: string;

    /**
     * @type {string}
     * @memberof CreateBulletinDto
     */
    description: string;

    /**
     * @type {Date}
     * @memberof CreateBulletinDto
     */
    createdDate: Date;

    /**
     * @type {string}
     * @memberof CreateBulletinDto
     */
    fileName?: string;

    /**
     * @type {Array<string>}
     * @memberof CreateBulletinDto
     */
    classids: Array<string>;

    /**
     * @type {string}
     * @memberof CreateBulletinDto
     */
    createdBy: string;
}
