/* tslint:disable */
/* eslint-disable */
/**
 * AYS API
 * AYS API Description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {

    /**
     * @type {Array<string>}
     * @memberof CreateUserDto
     */
    deviceTokens: Array<string>;

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    gsm: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    password: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    name: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    email: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    gender: CreateUserDtoGenderEnum;

    /**
     * @type {Date}
     * @memberof CreateUserDto
     */
    birth: Date;

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    occupation: string;

    /**
     * @type {Array<string>}
     * @memberof CreateUserDto
     */
    roles: Array<CreateUserDtoRolesEnum>;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateUserDtoGenderEnum {
    Male = 'male',
    Female = 'female'
}
/**
 * @export
 * @enum {string}
 */
export enum CreateUserDtoRolesEnum {
    Parent = 'parent',
    Teacher = 'teacher',
    Admin = 'admin'
}

