/* tslint:disable */
/* eslint-disable */
/**
 * AYS API
 * AYS API Description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ObjectId } from './object-id';
 /**
 * 
 *
 * @export
 * @interface CreateClassDto
 */
export interface CreateClassDto {

    /**
     * @type {string}
     * @memberof CreateClassDto
     */
    name: string;

    /**
     * @type {Array<ObjectId>}
     * @memberof CreateClassDto
     */
    teachers?: Array<ObjectId>;

    /**
     * @type {Array<ObjectId>}
     * @memberof CreateClassDto
     */
    students?: Array<ObjectId>;
}
