/* tslint:disable */
/* eslint-disable */
/**
 * AYS API
 * AYS API Description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface LoginDto
 */
export interface LoginDto {

    /**
     * @type {string}
     * @memberof LoginDto
     */
    gsm: string;

    /**
     * @type {string}
     * @memberof LoginDto
     */
    password: string;
}
