/* tslint:disable */
/* eslint-disable */
/**
 * AYS API
 * AYS API Description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ActivityDto } from './activity-dto';
 /**
 * 
 *
 * @export
 * @interface MultipleAcitivityDto
 */
export interface MultipleAcitivityDto {

    /**
     * @type {Array<ActivityDto>}
     * @memberof MultipleAcitivityDto
     */
    items: Array<ActivityDto>;
}
