/* tslint:disable */
/* eslint-disable */
/**
 * AYS API
 * AYS API Description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ObjectId } from './object-id';
 /**
 * 
 *
 * @export
 * @interface UpdateTeacherDto
 */
export interface UpdateTeacherDto {

    /**
     * @type {string}
     * @memberof UpdateTeacherDto
     */
    id?: string;

    /**
     * @type {string}
     * @memberof UpdateTeacherDto
     */
    gsm?: string;

    /**
     * @type {string}
     * @memberof UpdateTeacherDto
     */
    name?: string;

    /**
     * @type {string}
     * @memberof UpdateTeacherDto
     */
    email?: string;

    /**
     * @type {string}
     * @memberof UpdateTeacherDto
     */
    gender?: UpdateTeacherDtoGenderEnum;

    /**
     * @type {number}
     * @memberof UpdateTeacherDto
     */
    birth?: number;

    /**
     * @type {Array<ObjectId>}
     * @memberof UpdateTeacherDto
     */
    classid?: Array<ObjectId>;
}

/**
 * @export
 * @enum {string}
 */
export enum UpdateTeacherDtoGenderEnum {
    Male = 'male',
    Female = 'female'
}

