/* tslint:disable */
/* eslint-disable */
/**
 * AYS API
 * AYS API Description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ObjectId } from './object-id';
 /**
 * 
 *
 * @export
 * @interface UpdateStudentDto
 */
export interface UpdateStudentDto {

    /**
     * @type {number}
     * @memberof UpdateStudentDto
     */
    studentid?: number;

    /**
     * @type {string}
     * @memberof UpdateStudentDto
     */
    name?: string;

    /**
     * @type {string}
     * @memberof UpdateStudentDto
     */
    gender?: UpdateStudentDtoGenderEnum;

    /**
     * @type {Array<ObjectId>}
     * @memberof UpdateStudentDto
     */
    parents?: Array<ObjectId>;

    /**
     * @type {number}
     * @memberof UpdateStudentDto
     */
    birth?: number;

    /**
     * @type {string}
     * @memberof UpdateStudentDto
     */
    id?: string;

    /**
     * @type {any}
     * @memberof UpdateStudentDto
     */
    classid?: any;
}

/**
 * @export
 * @enum {string}
 */
export enum UpdateStudentDtoGenderEnum {
    Male = 'male',
    Female = 'female'
}

