/* tslint:disable */
/* eslint-disable */
/**
 * AYS API
 * AYS API Description
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export * from './apis/activity-api';
export * from './apis/auth-api';
export * from './apis/bulletin-api';
export * from './apis/class-api';
export * from './apis/notification-api';
export * from './apis/student-api';
export * from './apis/teacher-api';
export * from './apis/user-api';

